# Generated by Django 3.1 on 2020-08-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('site', models.CharField(max_length=64)),
                ('from_se', models.BooleanField()),
                ('se_activity_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
                ('site', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('pass_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='user_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.tag')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.user')),
            ],
        ),
        migrations.CreateModel(
            name='post_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.post_item')),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post_item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.user'),
        ),
    ]
