# Generated by Django 3.1 on 2020-09-01 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_note', '0002_auto_20200831_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_item',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='post_tag',
            new_name='PostTag',
        ),
        migrations.RenameModel(
            old_name='user_tag',
            new_name='UserTag',
        ),
    ]
