# Generated by Django 3.1 on 2020-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0003_auto_20200901_1429'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['url', 'entry_date', 'owner'], name='base_note_p_url_238078_idx'),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['post_key', 'tag_key'], name='base_note_p_post_ke_cacd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name', 'site'], name='base_note_t_tag_nam_bfea48_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['user_key', 'tag_key'], name='base_note_u_user_ke_9fd397_idx'),
        ),
    ]
