# Generated by Django 3.1 on 2020-09-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_note', '0004_auto_20200901_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='base_note_p_url_238078_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['url', 'entry_date'], name='base_note_p_url_9cae86_idx'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.post'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpost',
            index=models.Index(fields=['user_key', 'post_key'], name='base_note_u_user_ke_bb1e6f_idx'),
        ),
    ]
