# Generated by Django 3.1 on 2020-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0005_auto_20200901_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='pair_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='pair_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertag',
            name='pair_id',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
