# Generated by Django 3.1 on 2020-09-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0006_auto_20200901_1610'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='posttag',
            name='base_note_p_post_ke_cacd9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpost',
            name='base_note_u_user_ke_bb1e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertag',
            name='base_note_u_user_ke_9fd397_idx',
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['pair_id', 'post_key', 'tag_key'], name='base_note_p_pair_id_c3b2de_idx'),
        ),
        migrations.AddIndex(
            model_name='userpost',
            index=models.Index(fields=['pair_id', 'user_key', 'post_key'], name='base_note_u_pair_id_f26bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['pair_id', 'user_key', 'tag_key'], name='base_note_u_pair_id_3e635e_idx'),
        ),
    ]
