# Generated by Django 3.1 on 2020-09-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0007_auto_20200901_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
