# Generated by Django 3.1 on 2020-09-25 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_note', '0010_auto_20200924_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='marked_answer',
        ),
        migrations.CreateModel(
            name='Markedanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_answer', models.URLField()),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.post')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='markedanswer',
            index=models.Index(fields=['user_key', 'post_key'], name='base_note_m_user_ke_2ca888_idx'),
        ),
    ]
