# Generated by Django 3.1 on 2020-09-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0011_auto_20200924_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedanswer',
            name='answer_text',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
