# Generated by Django 3.1 on 2020-09-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_note', '0012_markedanswer_answer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.bucket')),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_note.post')),
            ],
        ),
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['bucket_name'], name='base_note_b_bucket__a5bad2_idx'),
        ),
        migrations.AddIndex(
            model_name='postbucket',
            index=models.Index(fields=['post_key', 'bucket_key'], name='base_note_p_post_ke_f9b23c_idx'),
        ),
    ]
